const CFG=window.INSUBRIA_CONFIG||{};
const sb=supabase.createClient(CFG.supabaseUrl||'',CFG.supabaseKey||'');
let currentUser=null,currentProfile=null,isAdmin=false,realtime=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=d=>new Date(d).toLocaleDateString('it-IT',{day:'2-digit',month:'short'});
const fmtDateTime=d=>new Date(d).toLocaleString('it-IT',{dateStyle:'short',timeStyle:'short'});
const initials=n=>(n||'?').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();
const adminRoles=['Presidente','Segretario','Amministratore'];

function showAuth(msg='',error=false){$('authMessage').textContent=msg;$('authMessage').className='auth-message '+(error?'error':'');$('authScreen').classList.remove('hidden');$('appShell').classList.add('hidden');}
function showApp(){$('authScreen').classList.add('hidden');$('appShell').classList.remove('hidden');}
function nav(page){if(!$(page))page='home';document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(page).classList.add('active');document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));history.replaceState(null,'','#'+page);}
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>nav(b.dataset.page));

async function boot(){
 if(!CFG.supabaseUrl||CFG.supabaseUrl.includes('TUO-PROGETTO')){showAuth('Configura prima config.js con URL e Publishable Key di Supabase.',true);return;}
 const {data:{session}}=await sb.auth.getSession();
 if(session) await startSession(session.user); else showAuth();
 sb.auth.onAuthStateChange(async(_event,session)=>{if(session) await startSession(session.user);else{currentUser=null;currentProfile=null;showAuth();}});
}
async function startSession(user){
 currentUser=user;
 let {data:p,error}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();
 if(error){showAuth(error.message,true);return;}
 if(!p){
   const claim=await sb.rpc('claim_member_invite',{p_email:(user.email||'').toLowerCase()});
   if(claim.error){await sb.auth.signOut();showAuth('Registrazione non autorizzata. Chiedi all’amministratore di invitarti.',true);return;}
   const q=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();
   if(q.error||!q.data){await sb.auth.signOut();showAuth('Registrazione non autorizzata. Chiedi all’amministratore di invitarti.',true);return;} p=q.data;
 }
 if(!p.is_active){await sb.auth.signOut();showAuth('Questo account non è più attivo come socio del Club.',true);return;}
 currentProfile=p;isAdmin=adminRoles.includes(p.role);
 $('profileName').value=p.name||'';$('profileRole').value=p.role||'Socio';$('profileRole').disabled=true;$('profilePhone').value=p.phone||'';$('profileEmail').value=p.email||user.email||'';await renderOwnAvatar();
 $('adminInfo').textContent=isAdmin?'Sei amministratore del Club.':'Profilo socio autenticato.';
 document.querySelectorAll('.admin-only').forEach(x=>x.style.display=isAdmin?'inline-flex':'none');
 $('postComposer').style.display=isAdmin?'block':'none';
 showApp();nav(location.hash.slice(1)||'home');subscribeRealtime();await renderAll();
 if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
}

$('loginBtn').onclick=async()=>{const email=$('authEmail').value.trim(),password=$('authPassword').value;if(!email||!password)return showAuth('Inserisci email e password.',true);const r=await sb.auth.signInWithPassword({email,password});if(r.error)showAuth(r.error.message,true);};
$('signupBtn').onclick=async()=>{const name=$('authName').value.trim(),email=$('authEmail').value.trim().toLowerCase(),password=$('authPassword').value;if(!name||!email||password.length<6)return showAuth('Inserisci nome, email e una password di almeno 6 caratteri.',true);const inv=await sb.rpc('is_email_invited',{p_email:email});if(inv.error)return showAuth("Impossibile verificare l'invito. Riprova.",true);if(!inv.data)return showAuth("Questa email non è stata invitata al Club. Chiedi all'amministratore di inserirti tra i soci.",true);const r=await sb.auth.signUp({email,password,options:{data:{name}}});if(r.error)return showAuth(r.error.message,true);if(r.data.session)await startSession(r.data.user);else showAuth('Account creato. Controlla la tua email per confermare l’account, poi accedi.');};
$('resetBtn').onclick=async()=>{const email=$('authEmail').value.trim();if(!email)return showAuth('Inserisci prima la tua email.',true);const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});showAuth(r.error?r.error.message:'Email per reimpostare la password inviata.');};
$('logoutBtn').onclick=()=>sb.auth.signOut();
$('postBtn').onclick=addPost;$('chatBtn').onclick=sendChat;$('newEventBtn').onclick=()=>openEvent();$('newMemberBtn').onclick=()=>openMemberForm();$('saveProfileBtn').onclick=saveProfile;$('profilePhotoInput').onchange=e=>uploadOwnAvatar(e.target.files?.[0]);$('photoInput').onchange=e=>addPhotos(e.target.files);$('docInput').onchange=e=>addDocs(e.target.files);$('closeModal').onclick=closeModal;

async function renderAll(){await Promise.all([renderMembers(),renderEvents(),renderPosts(),renderChat(),renderGallery(),renderDocs()]);await renderHome();}
async function renderHome(){
 const {data:events=[]}=await sb.from('events').select('*').order('event_date',{ascending:true}).gte('event_date',new Date().toISOString()).limit(3);
 $('statMembers').textContent=(await sb.from('profiles').select('id',{count:'exact',head:true}).eq('is_active',true)).count||0;
 $('statEvents').textContent=(await sb.from('events').select('id',{count:'exact',head:true})).count||0;
 $('statPosts').textContent=(await sb.from('posts').select('id',{count:'exact',head:true})).count||0;
 const ids=(events||[]).map(e=>e.id);let attendanceMap={};
 if(ids.length){const r=await sb.from('event_attendees').select('event_id,user_id,status').in('event_id',ids);for(const a of r.data||[]){attendanceMap[a.event_id]||={yes:0,mine:'pending'};if(a.status==='yes')attendanceMap[a.event_id].yes++;if(a.user_id===currentUser.id)attendanceMap[a.event_id].mine=a.status;}}
 $('homeEvents').innerHTML=events?.length?events.map(e=>eventCard(e,attendanceMap[e.id]||{yes:0,mine:'pending'})).join(''):'<div class="empty">Nessun evento inserito.</div>';
}

async function memberAvatar(path,size=120){if(!path)return '';const r=await sb.storage.from('avatars').createSignedUrl(path,3600);return r.data?.signedUrl||'';}
async function renderMembers(){
 const {data,error}=await sb.from('profiles').select('*').eq('is_active',true).order('name');if(error)return toast(error.message,true);
 const cards=[];for(const m of data||[]){const url=await memberAvatar(m.avatar_path);const avatar=url?`<img class="avatar" src="${url}" alt="Foto di ${esc(m.name)}">`:`<div class="avatar initials">${initials(m.name)}</div>`;cards.push(`<div class="card member" onclick="openMember('${m.id}')">${avatar}<div style="flex:1"><strong>${esc(m.name)}</strong><div class="muted">${esc(m.role||'Socio')}</div>${m.phone?`<div class="muted">📞 ${esc(m.phone)}</div>`:''}</div><div class="member-actions">${m.id===currentUser.id?'<span class="badge">Tu</span>':''}<span class="btn light">Dettagli</span></div></div>`);}
 $('membersList').innerHTML=cards.join('')||'<div class="empty">Nessun socio.</div>';
}
async function openMember(id){
 const {data:m,error}=await sb.from('profiles').select('*').eq('id',id).single();if(error||!m)return toast(error?.message||'Socio non trovato.',true);const url=await memberAvatar(m.avatar_path);const avatar=url?`<img class="member-detail-avatar" src="${url}" alt="Foto di ${esc(m.name)}">`:`<div class="member-detail-avatar initials">${initials(m.name)}</div>`;
 const action=m.id===currentUser.id?`<button class="btn light full" style="margin-top:10px" onclick="openMyProfile()">👤 Il tuo profilo</button>`:(isAdmin?`<button class="btn light full" style="margin-top:10px" onclick="openMemberEdit('${m.id}')">✏️ Modifica socio</button>`:'');
 $('modalContent').innerHTML=`<div class="member-detail-head">${avatar}<div><h2 style="margin:0">${esc(m.name)}</h2><div class="muted">${esc(m.role||'Socio')}</div></div></div><div class="card mini" style="margin-top:16px">${m.phone?`<div class="detail-row"><span>📞</span><a href="tel:${esc(m.phone)}">${esc(m.phone)}</a></div>`:''}${m.email?`<div class="detail-row"><span>✉️</span><a href="mailto:${esc(m.email)}">${esc(m.email)}</a></div>`:''}${action}</div>`;openModal();
}
function openMyProfile(){closeModal();nav('settings');}window.openMyProfile=openMyProfile;
async function openMemberForm(){
 if(!isAdmin)return;$('modalContent').innerHTML=`<h2>Invita nuovo socio</h2><p class="muted">Inserisci i dati del socio. L’app creerà un invito: il socio dovrà poi aprire l’app, usare la stessa email e scegliere una password. Il ruolo iniziale sarà <strong>Socio</strong>.</p><div class="formgrid"><input id="mEmail" class="input" type="email" placeholder="Email del socio"><input id="mName" class="input" placeholder="Nome e cognome"><input id="mPhone" class="input" placeholder="Telefono"></div><div class="role-note">Il socio non viene creato come account finché non completa la registrazione.</div><button class="btn" style="margin-top:12px" onclick="saveNewMember()">Crea invito</button>`;openModal();
}
async function saveNewMember(){
 if(!isAdmin)return;const email=$('mEmail').value.trim().toLowerCase(),name=$('mName').value.trim(),phone=$('mPhone').value.trim();if(!email||!name)return alert('Inserisci almeno nome e email.');const r=await sb.from('member_invites').upsert({email,name,phone,role:'Socio',created_by:currentUser.id,accepted_at:null},{onConflict:'email'});if(r.error)return toast(r.error.message,true);closeModal();toast(`Invito creato per ${email}. Il socio deve registrarsi nell’app usando questa stessa email.`);}
window.openMemberForm=openMemberForm;window.saveNewMember=saveNewMember;
async function openMemberEdit(id){
 if(!isAdmin)return;const {data:m,error}=await sb.from('profiles').select('*').eq('id',id).single();if(error||!m)return toast(error?.message||'Socio non trovato.',true);const url=await memberAvatar(m.avatar_path);const av=url?`<img class="member-detail-avatar" src="${url}" alt="Foto di ${esc(m.name)}">`:`<div class="member-detail-avatar initials">${initials(m.name)}</div>`;$('modalContent').innerHTML=`<h2>Modifica socio</h2><div class="profile-admin-photo">${av}<label class="btn light">📷 Cambia foto<input id="emPhoto" type="file" accept="image/*" hidden></label></div><div class="formgrid"><input id="emName" class="input" value="${esc(m.name)}" placeholder="Nome e cognome"><input id="emEmail" class="input" value="${esc(m.email||'')}" placeholder="Email" disabled><input id="emPhone" class="input" value="${esc(m.phone||'')}" placeholder="Telefono"><label class="field-label">Ruolo<select id="emRole" class="input"><option value="Socio">Socio</option><option value="Amministratore">Amministratore</option><option value="Segretario">Segretario</option><option value="Presidente">Presidente</option></select></label></div><div class="actions" style="margin-top:12px"><button class="btn" onclick="saveMemberEdit('${m.id}')">Salva modifiche</button>${m.id!==currentUser.id?`<button class="btn danger" onclick="removeMember('${m.id}')">Rimuovi dal Club</button>`:''}</div>`;$('emRole').value=m.role||'Socio';$('emPhoto').onchange=e=>uploadAvatarForUser(m.id,e.target.files?.[0]);openModal();
}
async function saveMemberEdit(id){if(!isAdmin)return;const payload={name:$('emName').value.trim(),phone:$('emPhone').value.trim(),role:$('emRole').value};if(!payload.name)return alert('Inserisci il nome.');const r=await sb.from('profiles').update(payload).eq('id',id);if(r.error)toast(r.error.message,true);else{closeModal();await renderMembers();toast('Scheda socio aggiornata.');}}
async function removeMember(id){if(!isAdmin||id===currentUser.id)return;if(!confirm('Rimuovere questo socio dal Club? L’account resterà memorizzato ma non potrà più accedere all’app.'))return;const r=await sb.from('profiles').update({is_active:false}).eq('id',id);if(r.error)return toast(r.error.message,true);closeModal();await renderMembers();toast('Socio rimosso dal Club.');}
window.openMemberEdit=openMemberEdit;window.saveMemberEdit=saveMemberEdit;window.removeMember=removeMember;

function mapLinks(location){if(!location)return '';const q=encodeURIComponent(location);return `<div class="map-links"><a class="btn light" href="https://www.google.com/maps/search/?api=1&query=${q}" target="_blank" rel="noopener">📍 Google Maps</a><a class="btn light" href="https://maps.apple.com/?q=${q}" target="_blank" rel="noopener">🗺️ Mappe</a></div>`;}
function eventCard(e,a={yes:0,mine:'pending'}){const mine=a.mine||'pending',yesClass=mine==='yes'?'rsvp-yes':'',noClass=mine==='no'?'selected rsvp-no':'';return `<div class="card event" onclick="openEvent('${e.id}')"><div class="event-date"><span>Data</span><strong>${fmtDate(e.event_date)}</strong></div><div style="flex:1;min-width:0"><strong>${esc(e.title)}</strong><div class="muted">${esc(e.location||'')} · ${new Date(e.event_date).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</div><div class="muted" style="margin-top:4px">${a.yes||0} partecipanti</div></div><div class="event-actions"><button class="btn ${yesClass}" onclick="event.stopPropagation();rsvp('${e.id}','yes')">${mine==='yes'?'✓ Partecipo':'Partecipo'}</button><button class="btn ${noClass}" onclick="event.stopPropagation();rsvp('${e.id}','no')">${mine==='no'?'✓ Non partecipo':'Non partecipo'}</button>${isAdmin?`<button class="btn light" onclick="event.stopPropagation();openEvent('${e.id}')">Modifica</button>`:''}</div></div>`;}
async function getAttendanceMap(events){const ids=(events||[]).map(e=>e.id),map={};if(!ids.length)return map;const r=await sb.from('event_attendees').select('event_id,user_id,status').in('event_id',ids);if(r.error){toast(r.error.message,true);return map;}for(const a of r.data||[]){map[a.event_id]||={yes:0,mine:'pending'};if(a.status==='yes')map[a.event_id].yes++;if(a.user_id===currentUser.id)map[a.event_id].mine=a.status;}return map;}
async function renderEvents(){const {data:events,error}=await sb.from('events').select('*').order('event_date');if(error)return toast(error.message,true);const map=await getAttendanceMap(events||[]);$('eventsList').innerHTML=events?.length?events.map(e=>eventCard(e,map[e.id]||{yes:0,mine:'pending'})).join(''):'<div class="empty">Nessun evento.</div>';}
async function openEvent(id=''){
 const result=id?await sb.from('events').select('*').eq('id',id).single():{data:{title:'',event_date:'',location:'',details:'',location_url:''}};const e=result.data;if(id&&(!e||result.error))return toast(result.error?.message||'Evento non trovato.',true);let attendance='';
 if(id){const r=await sb.from('event_attendees').select('status,user_id,profiles(name)').eq('event_id',id);const mine=r.data?.find(x=>x.user_id===currentUser.id)?.status||'pending';attendance=`<div class="card mini"><strong>La tua partecipazione</strong><div class="actions" style="margin-top:10px"><button class="btn ${mine==='yes'?'rsvp-yes':''}" onclick="rsvp('${id}','yes')">${mine==='yes'?'✓ Partecipo':'Partecipo'}</button><button class="btn light ${mine==='no'?'selected':''}" onclick="rsvp('${id}','no')">${mine==='no'?'✓ Non partecipo':'Non partecipo'}</button></div><div class="muted" style="margin-top:8px">${(r.data||[]).filter(x=>x.status==='yes').length} partecipanti</div></div>`;}
 const readOnly=!isAdmin&&id; $('modalContent').innerHTML=`<h2>${id?'Evento':'Nuovo evento'}</h2><label class="field-label">Titolo<input id="eTitle" class="input" placeholder="Titolo" value="${esc(e?.title||'')}"></label><label class="field-label">Data e ora<input id="eDate" class="input date-input" type="datetime-local" value="${e?.event_date?new Date(e.event_date).toISOString().slice(0,16):''}"></label><label class="field-label">Luogo / indirizzo<input id="eLoc" class="input" placeholder="Es. Via XX Settembre 1, Varese" value="${esc(e?.location||'')}"></label><div class="map-links form-map">${e?.location?mapLinks(e.location):''}</div><label class="field-label">Descrizione<textarea id="eDetails" class="textarea" placeholder="Descrizione">${esc(e?.details||'')}</textarea></label>${attendance}<div class="actions admin-only"><button class="btn" onclick="saveEvent('${id}')">Salva</button>${id?`<button class="btn danger" onclick="deleteEvent('${id}')">Elimina</button>`:''}</div>`;
 if(readOnly){document.querySelectorAll('#modalContent .admin-only').forEach(x=>x.style.display='none');document.querySelectorAll('#modalContent input,#modalContent textarea').forEach(x=>x.disabled=true);}
 openModal();
}
async function saveEvent(id){if(!isAdmin)return;const title=$('eTitle').value.trim(),location=$('eLoc').value.trim();if(!title||!$('eDate').value)return alert('Inserisci titolo e data.');const payload={title,event_date:new Date($('eDate').value).toISOString(),location,details:$('eDetails').value.trim(),created_by:currentUser.id};const r=id?await sb.from('events').update(payload).eq('id',id):await sb.from('events').insert(payload);if(r.error)toast(r.error.message,true);else{closeModal();renderAll();}}
async function deleteEvent(id){if(!isAdmin||!confirm('Eliminare evento?'))return;const r=await sb.from('events').delete().eq('id',id);if(r.error)toast(r.error.message,true);else{closeModal();renderAll();}}
async function rsvp(eventId,status){const r=await sb.from('event_attendees').upsert({event_id:eventId,user_id:currentUser.id,status,updated_at:new Date().toISOString()},{onConflict:'event_id,user_id'}).select();if(r.error){toast(r.error.message,true);return;}await renderEvents();await renderHome();if($('modal').classList.contains('open'))await openEvent(eventId);}

async function renderPosts(){const {data,error}=await sb.from('posts').select('id,text,created_at,author_id,profiles(name)').order('created_at',{ascending:false}).limit(100);if(error)return toast(error.message,true);$('postsList').innerHTML=data?.length?data.map(p=>`<div class="card"><div class="post-head"><div><strong>${esc(p.profiles?.name||'Socio')}</strong><div class="muted">${fmtDateTime(p.created_at)}</div></div>${isAdmin?`<div class="actions"><button class="btn light" onclick="openPostEdit('${p.id}')">Modifica</button><button class="btn danger" onclick="deletePost('${p.id}')">Elimina</button></div>`:''}</div><div style="margin-top:7px">${esc(p.text)}</div></div>`).join(''):'<div class="empty">Nessun messaggio.</div>';}
async function addPost(){if(!isAdmin)return;const text=$('postText').value.trim();if(!text)return;const r=await sb.from('posts').insert({author_id:currentUser.id,text});if(r.error)toast(r.error.message,true);else{$('postText').value='';renderPosts();renderHome();}}
async function openPostEdit(id){if(!isAdmin)return;const r=await sb.from('posts').select('*').eq('id',id).single();if(r.error)return toast(r.error.message,true);$('modalContent').innerHTML=`<h2>Modifica messaggio</h2><textarea id="editPostText" class="textarea">${esc(r.data.text)}</textarea><button class="btn" style="margin-top:10px" onclick="savePostEdit('${id}')">Salva</button>`;openModal();}
async function savePostEdit(id){if(!isAdmin)return;const text=$('editPostText').value.trim();if(!text)return;const r=await sb.from('posts').update({text}).eq('id',id);if(r.error)toast(r.error.message,true);else{closeModal();renderPosts();}}
async function deletePost(id){if(!isAdmin||!confirm('Eliminare questo messaggio dalla bacheca?'))return;const r=await sb.from('posts').delete().eq('id',id);if(r.error)toast(r.error.message,true);else renderPosts();}

async function renderChat(){const {data,error}=await sb.from('chat_messages').select('id,text,created_at,author_id,profiles(name)').order('created_at',{ascending:true}).limit(200);if(error)return toast(error.message,true);$('chatAdminActions').style.display=isAdmin?'flex':'none';$('chatList').innerHTML=data?.length?data.map(c=>`<div class="bubble ${c.author_id===currentUser.id?'mine':''}"><div class="chat-head"><strong>${esc(c.profiles?.name||'Socio')}</strong>${isAdmin?`<button class="delete-mini" title="Elimina messaggio" onclick="deleteChatMessage('${c.id}')">×</button>`:''}</div><div>${esc(c.text)}</div><div class="muted">${new Date(c.created_at).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</div></div>`).join(''):'<div class="empty">Nessun messaggio.</div>';$('chatList').scrollTop=$('chatList').scrollHeight;}
async function sendChat(){const text=$('chatText').value.trim();if(!text)return;const r=await sb.from('chat_messages').insert({author_id:currentUser.id,text});if(r.error)toast(r.error.message,true);else{$('chatText').value='';renderChat();}}
async function deleteChatMessage(id){if(!isAdmin||!confirm('Eliminare questo messaggio?'))return;const r=await sb.from('chat_messages').delete().eq('id',id);if(r.error)toast(r.error.message,true);else renderChat();}
async function clearChat(){if(!isAdmin||!confirm('Eliminare tutti i messaggi della chat?'))return;const r=await sb.from('chat_messages').delete().gte('created_at','1970-01-01T00:00:00Z');if(r.error)toast(r.error.message,true);else renderChat();}

async function addPhotos(files){if(!isAdmin)return;for(const f of files){const path=`${currentUser.id}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('gallery').upload(path,f,{upsert:false});if(up.error){toast(up.error.message,true);continue;}const ins=await sb.from('gallery_photos').insert({owner_id:currentUser.id,file_path:path,file_name:f.name});if(ins.error)toast(ins.error.message,true);} $('photoInput').value='';renderGallery();}
async function renderGallery(){const {data,error}=await sb.from('gallery_photos').select('*').order('created_at',{ascending:false}).limit(100);if(error)return toast(error.message,true);const cards=[];for(const p of data||[]){const u=await sb.storage.from('gallery').createSignedUrl(p.file_path,3600);cards.push(`<div class="photo-card"><button class="photo-open" onclick="openPhoto('${p.id}')"><img src="${u.data?.signedUrl||''}" alt="${esc(p.file_name)}"></button><div class="photo-caption">${esc(p.file_name)}</div>${isAdmin?`<button class="btn danger photo-delete" onclick="deletePhoto('${p.id}',event)">Elimina</button>`:''}</div>`);} $('galleryList').innerHTML=cards.join('')||'<div class="empty">Nessuna foto.</div>';}
async function openPhoto(id){const r=await sb.from('gallery_photos').select('*').eq('id',id).single();if(r.error)return toast(r.error.message,true);const u=await sb.storage.from('gallery').createSignedUrl(r.data.file_path,3600);$('modalContent').innerHTML=`<h2>${esc(r.data.file_name)}</h2><img class="lightbox-image" src="${u.data?.signedUrl||''}" alt="${esc(r.data.file_name)}">`;openModal();}
async function deletePhoto(id,ev){if(ev)ev.stopPropagation();if(!isAdmin||!confirm('Eliminare questa foto?'))return;const r=await sb.from('gallery_photos').select('file_path').eq('id',id).single();if(r.error)return toast(r.error.message,true);const d=await sb.storage.from('gallery').remove([r.data.file_path]);if(d.error)return toast(d.error.message,true);const x=await sb.from('gallery_photos').delete().eq('id',id);if(x.error)return toast(x.error.message,true);renderGallery();}

async function addDocs(files){if(!isAdmin)return;for(const f of files){const path=`${currentUser.id}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('documents').upload(path,f,{upsert:false});if(up.error){toast(up.error.message,true);continue;}const ins=await sb.from('documents').insert({owner_id:currentUser.id,file_path:path,file_name:f.name});if(ins.error)toast(ins.error.message,true);} $('docInput').value='';renderDocs();}
async function renderDocs(){const {data,error}=await sb.from('documents').select('*').order('created_at',{ascending:false});if(error)return toast(error.message,true);const out=[];for(const d of data||[]){const u=await sb.storage.from('documents').createSignedUrl(d.file_path,3600);out.push(`<div class="card doc"><div class="docicon">FILE</div><div style="flex:1"><strong>${esc(d.file_name)}</strong><div class="muted">${fmtDateTime(d.created_at)}</div></div><a class="btn light" href="${u.data?.signedUrl||'#'}" target="_blank" rel="noopener">Apri</a>${isAdmin?`<button class="btn danger" onclick="deleteDoc('${d.id}')">Elimina</button>`:''}</div>`);} $('docsList').innerHTML=out.join('')||'<div class="empty">Nessun documento.</div>';}
async function deleteDoc(id){if(!isAdmin||!confirm('Eliminare questo documento?'))return;const r=await sb.from('documents').select('file_path').eq('id',id).single();if(r.error)return toast(r.error.message,true);const d=await sb.storage.from('documents').remove([r.data.file_path]);if(d.error)return toast(d.error.message,true);const x=await sb.from('documents').delete().eq('id',id);if(x.error)return toast(x.error.message,true);renderDocs();}

async function renderOwnAvatar(){const url=await memberAvatar(currentProfile?.avatar_path);$('profilePhotoPreview').innerHTML=url?`<img class="profile-photo" src="${url}" alt="La tua foto">`:`<div class="profile-photo initials">${initials(currentProfile?.name)}</div>`;}
async function uploadAvatarForUser(userId,file){if(!file||!isAdmin&&userId!==currentUser.id)return;const old=await sb.from('profiles').select('avatar_path').eq('id',userId).single();const path=`${userId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('avatars').upload(path,file,{upsert:false});if(up.error)return toast(up.error.message,true);const r=await sb.from('profiles').update({avatar_path:path}).eq('id',userId);if(r.error){await sb.storage.from('avatars').remove([path]);return toast(r.error.message,true);}if(old.data?.avatar_path&&old.data.avatar_path!==path)await sb.storage.from('avatars').remove([old.data.avatar_path]);if(userId===currentUser.id){currentProfile.avatar_path=path;await renderOwnAvatar();}else{await renderMembers();closeModal();toast('Foto del socio aggiornata.');}}
async function uploadOwnAvatar(file){await uploadAvatarForUser(currentUser.id,file);}
async function saveProfile(){const payload={name:$('profileName').value.trim(),phone:$('profilePhone').value.trim()};if(!payload.name)return alert('Inserisci il nome.');const r=await sb.from('profiles').update(payload).eq('id',currentUser.id);if(r.error)toast(r.error.message,true);else{currentProfile={...currentProfile,...payload};$('profileName').value=currentProfile.name||'';$('profilePhone').value=currentProfile.phone||'';toast('Profilo aggiornato.');await renderOwnAvatar();renderMembers();}}
function subscribeRealtime(){realtime.forEach(x=>sb.removeChannel(x));realtime=[];['posts','chat_messages','events','event_attendees','gallery_photos','documents','profiles'].forEach(table=>{const ch=sb.channel('insubria-'+table).on('postgres_changes',{event:'*',schema:'public',table},()=>{if(table==='posts')renderPosts();else if(table==='chat_messages')renderChat();else if(table==='events'||table==='event_attendees'){renderEvents();renderHome();}else if(table==='gallery_photos')renderGallery();else if(table==='documents')renderDocs();else if(table==='profiles'){renderMembers();renderHome();}}).subscribe();realtime.push(ch);});}
function openModal(){$('modal').classList.add('open')}function closeModal(){$('modal').classList.remove('open')}
function toast(msg,error=false){if(!msg)return;const old=$('authMessage').textContent;$('authMessage').textContent=msg;$('authMessage').className='auth-message '+(error?'error':'');setTimeout(()=>{$('authMessage').textContent=old;$('authMessage').className='auth-message';},3500);}
window.openEvent=openEvent;window.openMember=openMember;window.saveEvent=saveEvent;window.deleteEvent=deleteEvent;window.rsvp=rsvp;window.addPost=addPost;window.sendChat=sendChat;window.openMemberEdit=openMemberEdit;window.saveMemberEdit=saveMemberEdit;window.deletePost=deletePost;window.openPostEdit=openPostEdit;window.savePostEdit=savePostEdit;window.deleteChatMessage=deleteChatMessage;window.clearChat=clearChat;window.openPhoto=openPhoto;window.deletePhoto=deletePhoto;window.deleteDoc=deleteDoc;
boot();
